cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove, cart_object

app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('items/', cart_detail, name='cart_detail'),
    path('items/data/', cart_object, name='cart-object')
]

orders/urls.py
from django.urls import path
from .views import order_create,  payment_completed, payment_canceled, admin_order_detail, admin_order_pdf, stripe_webhook


app_name='orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    # path('process/', payment_process, name='process'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_canceled, name='canceled'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
    path('webhook/', stripe_webhook, name='webhook'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,2)]
# quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.HiddenInput(), initial=1)
    override   = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import JsonResponse
import json
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm

def cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    cart.add(product=product)
    cart_len = cart.__len__()
    cart_cost = cart.get_total_price()
    response_data = {
        "cart_count": cart_len,
        "cart_cost": cart_cost
    }
    return JsonResponse({'data': response_data})
    

def cart_remove(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    cart.remove(product=product)
    cart_len = cart.__len__()
    cart_cost = cart.get_total_price()
    response_data = {
        "cart_count": cart_len,
        "cart_cost":  cart_cost
    }
    return JsonResponse({'data': response_data}, safe=False)
 
def cart_detail(request):
    cart = Cart(request)
    cart_items = cart.__iter__()  
    total_price = cart.get_total_price()  
    return render(request, 'cart/cart_detail.html', {'cart_items': cart_items, 'total_price': total_price})

def cart_object(request):
    cart = Cart(request)
    cart_items = cart.__iter__()
    cart_items_list = []
    for item in cart_items:
        cart_items_list.append({
            'product': item['product'].name,
            'quantity': item['quantity'],
            'price': item['price'],
            'total': item['price'] * item['quantity']
        })
    response_data = {
        'cart_items': cart_items_list, 
    }
    return JsonResponse(response_data)

    
    # return JsonResponse({'data': data}, safe=False)
    

# def cart_add(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     form = CartAddProductForm(request.POST)
#     if form.is_valid():
#         cd = form.cleaned_data
#         cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
#     return redirect('cart:cart_detail')

# def cart_remove(request, product_id):
#     cart = Cart(request)
#     product = get_object_or_404(Product, id=product_id)
#     cart.remove(product)
#     return redirect('products:list')

# def cart_detail(request):
#     cart = Cart(request)
#     for item in cart:
#         item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override':True}) 
#     return render(request, 'cart/cart_detail.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends 'account/base.html' %}
{% block content %}
<div class="flex flex-col max-w-3xl mx-auto p-6 space-y-4 sm:p-10 dark:bg-gray-900 dark:text-gray-100 shadow-2xl outline-dashed outline-2 my-6">
	<h2 class="text-2xl text-center font-semibold">Your cart</h2>
	<ul class="flex flex-col divide-y divide-gray-700">
        {% for item in cart_items %}
		<li class="flex flex-col py-6 sm:flex-row sm:justify-between">
			<div class="flex w-full space-x-2 sm:space-x-4">
				<img class="flex-shrink-0 object-cover w-20 h-20 dark:border-transparent rounded outline-none sm:w-32 sm:h-32 dark:bg-gray-500" src="{{ item.product.image.url }}" alt="Polaroid camera">
				<div class="flex flex-col justify-between w-full pb-4">
					<div class="flex justify-between w-full pb-2 space-x-2">
						<div class="space-y-1">
							<h3 class="text-lg font-semibold leadi sm:pr-8">{{ item.product.name }}</h3>
							<p class="text-sm dark:text-gray-400 itemQuantity" >{{ item.quantity }}</p>
                            <p class="text-lg font-semibold">{{ item.price }}</p>
						</div>
						<div class="text-right">
							
							<p class="text-lg dark:text-gray-600 itemTotalPrice">{{ item.total_price }}</p>
						</div>
					</div>
					<div class="flex text-sm divide-x">
						<button type="button" class="flex items-center px-2 py-1 pl-0 space-x-1">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-4 h-4 fill-current">
								<path d="M96,472a23.82,23.82,0,0,0,23.579,24H392.421A23.82,23.82,0,0,0,416,472V152H96Zm32-288H384V464H128Z"></path>
								<rect width="32" height="200" x="168" y="216"></rect>
								<rect width="32" height="200" x="240" y="216"></rect>
								<rect width="32" height="200" x="312" y="216"></rect>
								<path d="M328,88V40c0-13.458-9.488-24-21.6-24H205.6C193.488,16,184,26.542,184,40V88H64v32H448V88ZM216,48h80V88H216Z"></path>
							</svg>
							<button class="py-1 px-4 border   remove-button " data-url="{% url 'cart:cart_remove' item.product.id %}">-</button>
						</button>
						<button type="button" class="flex items-center px-2 py-1 space-x-1">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-4 h-4 fill-current">
								<path d="M453.122,79.012a128,128,0,0,0-181.087.068l-15.511,15.7L241.142,79.114l-.1-.1a128,128,0,0,0-181.02,0l-6.91,6.91a128,128,0,0,0,0,181.019L235.485,449.314l20.595,21.578.491-.492.533.533L276.4,450.574,460.032,266.94a128.147,128.147,0,0,0,0-181.019ZM437.4,244.313,256.571,425.146,75.738,244.313a96,96,0,0,1,0-135.764l6.911-6.91a96,96,0,0,1,135.713-.051l38.093,38.787,38.274-38.736a96,96,0,0,1,135.765,0l6.91,6.909A96.11,96.11,0,0,1,437.4,244.313Z"></path>
							</svg>
							<span>Add to favorites</span>
						</button>
					</div>
				</div>
			</div>
		</li>
		{% endfor %}
		
	</ul>
	<div class="space-y-1 text-right">
		<p>Total amount:
			<span class="font-semibold" id="totalPrice">{{ total_price }} €</span>
		</p>
		
	</div>
	<div class="flex justify-end space-x-4">
		
		<div class="flex justify-center">
            <a href="{% url 'orders:order_create' %}" class=" flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">Checkout</a>
        </div>
	</div>
</div>
   

<script>
    document.addEventListener('DOMContentLoaded', ()=>{
        const removeFromCart  = document.querySelectorAll('.remove-button');
        const cartInfoElement = document.getElementById('cart-info');
        const totalPrice      = document.querySelector('#totalPrice')
        const svg = '<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>'
  
        removeFromCart.forEach((button)=>{
            button.addEventListener('click', (event)=>{
                const url = event.target.dataset.url
                removeItem(url)
            })
        })
        
        async function removeItem(url){
            try{
                const response = await fetch(url)
                const data = await response.json()
                if (data){
                const cartCount = data.data.cart_count
                const cartCost  = data.data.cart_cost
                if(cartInfoElement && totalPrice){
                    cartInfoElement.innerHTML = `${svg} £${cartCost}  ${cartCount} item${cartCount !== 1 ? 's' : ''}, `;
                    totalPrice.innerHTML = `${cartCost}`
                    updatedUI()
                }
                
            }  
            }catch(error){
                console.error('There was a problem', error)
            }            
        }
        async function updatedUI(){
            const url = '/cart/items/data/'
            try{
                const response = await fetch(url)
                const data = await response.json()
                const cartItems = data.cart_items
                cartItems.forEach((el, index)=>{
                    console.log(el)
                    const product = el.product
                    const price = el.price
                    const quantity = el.quantity
                    const total = el.total
                     // Update the corresponding elements in the DOM using the index
                    const itemQuantityElements = document.querySelectorAll('.itemQuantity');
                    const itemTotalPriceElements = document.querySelectorAll('.itemTotalPrice');

                    if (itemQuantityElements[index] && itemTotalPriceElements[index]) {
                        itemQuantityElements[index].innerHTML = quantity;
                        itemTotalPriceElements[index].innerHTML = total;
                    }
                    //How do i update the correct object in the DOM?
                    // const ui = `
                    // <div class="space-y-1">
					// 		<h3 class="text-lg font-semibold leadi sm:pr-8">${product}</h3>
					// 		<p class="text-sm dark:text-gray-400">${price}</p>
                    //         <p class="text-lg font-semibold">${quantity}</p>
                    //         <p class="text-lg dark:text-gray-600">${total}</p>
					// </div>
						
                    // `

                    // cartInfoHolder.insertAdjacentHTML('afterbegin', ui)
                })
            }catch(error){
                console.error('There was a problem', error)
            }
        }
        
    })
</script>
    


{% endblock %}




<div class="max-w-4xl mx-auto p-12 min-h-screen">
    <table class="w-full text-sm text-left shadow-2xl ">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200">
            <tr>
                <th scope="col" class="py-3 px-6">
                    Product name
                </th>
                <th scope="col" class="py-3 px-6">
                    Price
                </th>
                <th scope="col" class="py-3 px-6">
                    Remove
                </th>
                <th scope="col" class="py-3 px-6">
                    Price
                </th>
                <th scope="col" class="py-3 px-6">
                    Total
                </th>
            </tr>
        </thead>
        <tbody>
            <tr class="bg-white border-b dark:bg-gray-800 ">
                <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap">
                    {{ product.name }}
                </th>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                      {{ item.update_quantity_form.quantity }}
                      {{ item.update_quantity_form.override }}
                      <input type="submit" value="update">
                      {% csrf_token %}
                    </form>
                  </td>
                  <td>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                      <input type="submit" value="Remove" class="cursor-pointer py-4 px-6">
                      {% csrf_token %}
                    </form>
                  </td>
                <td class="py-4 px-6">
                    £{{ product.price }}
                </td>
                <td class="py-4 px-6">
                    £{{ cart.get_total_price }}
                </td>
            </tr>
         
        </tbody>
    </table>
    <div class="flex justify-center">
        <a href="{% url 'orders:order_create' %}" class=" flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">Checkout</a>
    </div>
</div>
<!-- <td class="num">${{ item.price }}</td>
<td class="num">${{ item.total_price }}</td> -->

</tr>