accounts/urls.py
from django.urls import path
from .views import dashboard, user_orders, delete_account

app_name = 'accounts'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('user_orders/', user_orders, name='user_orders'),
    path('delete_account/', delete_account, name='delete_account')
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove, cart_object

app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('items/', cart_detail, name='cart_detail'),
    path('items/data/', cart_object, name='cart-object')
]

product/urls.py
from django.urls import path
from .views import ProductList,ProductDetail, ProductDownloadView

app_name = 'products'

urlpatterns =  [
    path('', ProductList.as_view(), name='list'),
    path('<int:id>/<slug:slug>/', ProductDetail.as_view(), name='detail'),
    path('<int:id>/<slug:slug>/download/', ProductDownloadView.as_view(), name='download')
]

stats/urls.py
from django.urls import path
from .views import get_stats

app_name = 'stats'

urlpatterns = [
    path('', get_stats, name='stats')
]

stats/models.py
from django.db import models

class Problems(models.Model):
    issue   = models.CharField(max_length=255)
    figure  = models.IntegerField()

    def __str__(self):
        return self.issue

stats/views.py
from django.shortcuts import render
from django.db.models import Count, Q
from .models import Problems
import json

def get_stats(request):
    stat_nos = Problems.objects.values('figure')
    stat_issue = Problems.objects.values('issue')
    
   
    issue_series = list()
    figure_series = list()
  
    for entry in stat_nos:
        figure_series.append(entry['figure'])
    for entry in stat_issue:
        issue_series.append(entry['issue'])

    context = {
        'issue_series': json.dumps(issue_series),
        'figure_series': json.dumps(figure_series)
    }

    return render(request, 'stats.html', context)

templates/contact-form.html
{% extends 'account/base.html' %}
{% block content %}
<div class="max-w-sm mx-auto p-6">
    <h3 class="text-2xl text-center">Contact</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="flex justify-center">
            <input type="submit" value="submit" class="py-2 px-8 border bg-blue-700 hover:bg-blue-900 text-white shadow-lg">
        </div>
    </form>
</div>

{% endblock %}

templates/footer.html
<footer  class="sticky top-[100vh]" >
<div id="footerSvg" class="bg-gray-700 text-white grid grid-cols-1 lg:grid-cols-2 gap-6 p-12 place-content-center ">
    
    <div class="border p-12">
        <h3 class="text-lg text-center p-2">Get in touch </h3>
        <div class="flex justify-center">
            <a href="{% url 'contact_view' %}" class="py-2 px-8 border bg-blue-800 Hover:bg-blue-900">Contact</a>
        </div>
       
    </div>
    <div class="border p-12 shadow-2xl">
        <h3 class="text-lg text-center p-2">Privacy Policy</h3>
        <div class="flex justify-center">
            <a href="{% url 'policy' %}" class="py-2 px-8 border bg-blue-800 Hover:bg-blue-900">View</a>
        </div>
       </div>
  
       

      
</div>
<div class="bg-gray-800 text-gray-400">Course cover credit Image by <a href="https://pixabay.com/users/mohamed_hassan-5229782/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=7323725">Mohamed Hassan</a> from <a href="https://pixabay.com//?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=7323725">Pixabay</a></div>


    <div class="text-center text-sm bg-gray-900 p-6 text-slate-100">The Care Guild {% now "Y" %}</div>
</footer>

templates/home.html
{% extends "account/base.html" %}
{% load static %}
{% block content %}
<div class="max-w-6xl mx-auto">
    <div class="grid  lg:grid-cols-3">
        <div class="p-12 lg:p-6 lg:col-span-2">
          
            <h2 class="text-4xl  lg:text-6xl font-bold my-6 text-gray-700">Mental Health Awareness Course</h2>
            <h4 class="text-2xl lg:text-4xl text-blue-700 font-bold my-6">Enrichment for your family, friend or business</h4>
            <ul class="text-gray-800 text-lg lg:text-xl">
                <li class="  border-gray-200 w-full mb-2">Mental Health problems are common. Did you know:</li>
                <li class="  border-gray-200 w-full " >1 in 4 people will experience a mental health problem of some kind each year in England</li>
                <li class="  border-gray-200 w-full">1 in 6 people report experiencing a common mental health problem (like anxiety and depression) in any given week in England</li>
            </ul>
            <small>Source:<a href='https://www.mind.org.uk/information-support/types-of-mental-health-problems/statistics-and-facts-about-mental-health/how-common-are-mental-health-problems/'>mind.org.uk</a></small>
                <div class="flex items-center justify-center my-6"></div>
        </div>
                <div class="grid content-center place-content-center overflow-hidden" >
                    <div class="  lg:h-60 lg:w-60" id="rot"></div>
                </div>
    </div>
</div>
{% include 'product/product_list.html' %}

<header class="text-center mx-auto mb-12 lg:px-20">
    
    <p class=" text-xl mx-auto pb-2">More Statistics.</p>
</header>
<div class="grid grid-cols-1 lg:grid-cols-3 p-12 lg:p-6">
    <div class="border p-4">
        <img src="{% static 'img/depressed.svg' %}" class="h-12 w-12 text-blue-900 mb-2">
        <p>People reporting self-harm went up by 62% between the years 2000–2014 (that means it more than doubled)</p>
    </div>
    <div class="border p-4">
        <img src="{% static 'img/suicide.svg' %}" class="h-12 w-12  mb-2">
        <p>People reporting having had suicidal thoughts within the past year went up by 30% between the years 2000–2014 </p>
    </div>
    <div class="border p-4">
        <img src="{% static 'img/despair.svg' %}" class="h-12 w-12  mb-2">
        <p>The number of people who self-harm or have suicidal thoughts is rising faster than the number of people experiencing mental health problems overall</p>
    </div>

</div>
{% endblock %}

templates/navbar.html
{% load static %}
{% url 'products:list' as home_url %}
{% url 'projects' as projects_url %}
{% url 'accounts:dashboard' as dashboard_url %}
 

<div class="navbar text-white  text-lg md:text-xl ">
 
 
    <div class="navbar_link navbar_btn  ">
    <svg xmlns="http://www.w3.org/2000/svg" id="toggleBtn" class="h-12 w-12 text-gold"  fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
    </div>
    
   <nav class="navbar_items rev_navbar_toggleShow">
     <div class="navbar_link link p-1 rounded" {% if request.path == home_url %}class="text-gray-800 p-1 rounded "{% endif %}>
        <a href="{{ home_url }}"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
        </svg>
        </a>
     </div>
     <!-- <div class="navbar_link link p-1 rounded" {% if request.path == projects_url  %}class="text-gray-800p-1 rounded "{% endif %}>
        <a href="{{ projects_url }}">Projects</a>
     </div>
     <div class="navbar_link link p-1 rounded" {% if request.path == prices_url   %}class="text-gray-800 p-1 rounded "{% endif %} >
        <a href="{{ prices_url }}">Prices</a>
     </div> -->
    
   </nav>
   <!-- <span class="navbar_link navbar_link-brand " > -->
    <!-- <img src="{% static 'img/' %}" alt="logo" class="nav_img h-20 w-20 mx-auto logoMain"> -->
    <!-- </span> -->
   <nav class="navbar_items navbar_items-right rev_navbar_toggleShow p-6">
     <div class="navbar_link">
            {% with total_items=cart|length %}
                    <a href="{% url 'cart:cart_detail' %}" id="cart-info" class="mr-6 ">
                       <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                        </svg> £{{ cart.get_total_price }}, {{ total_items }} item{{ total_items|pluralize }}
                    </a>
            {% endwith %}
     </div>
     {% if user.is_authenticated %}
            <div class="navbar_link "><a href="{{ dashboard_url }}"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg> Account</a></div>
            <div class="navbar_link "><a href="{% url 'account_logout' %}"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg> Log Out</a></div>
            {% else %}
            <div class="navbar_link "><a href="{% url 'account_login' %}"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
            </svg> LogIn</a></div>
            <div class="navbar_link "><a href="{% url 'account_signup' %}"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
            </svg> Sign Up</a></div>
            {% endif %}
   </nav>
 </div>



 <!-- {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                
                    <a href="{% url 'cart:cart_detail' %}" id="cart-info">
                        {{ total_items }} item{{ total_items|pluralize }}, £{{ cart.get_total_price }}<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                        </svg>
                    </a>
                {% else %}
                <svg xmlns="http://www.w3.org/2000/svg"  class="h-6 w-6 inline" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                </svg>0
                {% endif %}
            {% endwith %} -->

templates/policy.html
{% extends 'account/base.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col mx-auto">

        
        <p>
            <h1>PRIVACY STATEMENT</h1>

        <p>   This website privacy policy template is based on a free document supplied by The Legal Stop Limited through its website  <a href="http://www.thelegalstop.co.uk">Legal Stop</a></p> 
            
            
            
        <br>
            
            Your privacy is important to redsleeves.co.uk We are committed to safeguarding the privacy of our website visitors; this privacy statement sets out how we will treat your personal information.
        <br>  
            <h3>Personal Data Collection</h3>

            <p>
            
            redsleeves.co.uk may collect, store and use the following kinds of personal information:
            
            information about your computer and about your visits to and use of this websites (which may include your IP address, geographical location, browser type and version, referral source, entry page, exit page, length of visit, number of page views, route taken through this website, and similar information);
            information relating to any transactions carried out between you and us on or in relation to this website, including information relating to any purchases you make of our goods or services;
            information that you provide to us for the purpose of registering with us;
             information that you provide to us for the purpose of subscribing to our website services, email notifications and/or newsletters; and
            any other information that you choose to send to us.
        </p>


            
            <h5>Using Personal Data</h5>
        <p>

        
            Personal information submitted to us via this website will be used for the purposes specified in this privacy statement or in relevant parts of the website.
            
            <h5>We may use your personal data to:</h5>
            <ul>
                <li>administer the website;</li>
                <li>improve your browsing experience;</li>
                <li>enable your use of the services available on the website;</li>
                <li>send to you goods purchased via the website, and supply to you services purchased via the website;</li>
                <li>send statements and invoices to you, and collect payments from you;</li>
                <li>send you general non-marketing commercial communications;</li>
                <li>send you email notifications which you have specifically requested;</li>
                <li> send to you our newsletter and other marketing communications relating to our business or the businesses of carefully-selected third parties which we think may be of interest to you by post or, where you have specifically agreed to this, by email  and you can inform us at any time if you no longer require marketing communications; and </li>
                <li>deal with enquiries and complaints made by or about you relating to the website.</li>
            </ul>
            
            
            
            
            
            
            
           
            
        </p>  
           <h5> Personal Data Security</h5>
            
            We will take reasonable technical and organisational precautions to prevent the loss, misuse or alteration of your personal information. 
            
             redsleeves.co.uk will store all the personal data you provide on its secure servers. Information relating to electronic transactions entered into via this website will be protected by encryption technology.
            
            You are responsible for keeping your password and user details confidential. We will not ask you for your password except when you log in to the website.
            
            Disclosures
            
            We may disclose information about you to any of our employees, officers, agents, suppliers or subcontractors insofar as reasonably necessary for the purposes as set out in this privacy statement. 
            
            In addition, we may disclose your personal information: 
            
            to the extent that we are required to do so by law;
            in connection with any legal proceedings or prospective legal proceedings;
            in order to establish, exercise or defend our legal rights (including providing information to others for the purposes of fraud prevention and reducing credit risk); and
            to any person who we reasonably believe may apply to a court or other competent authority for disclosure of that personal information where, in our reasonable opinion, such court or authority would be reasonably likely to order disclosure of that personal information.
            
            Except as provided in this privacy statement, we will not provide your information to third parties.
            
            
            
            Cross-border Data Transfers
            
            Information that redsleeves.co.uk collects may be stored and processed in and transferred between any of the countries in which we operate to enable the use of the information in accordance with this privacy statement.
            
            In addition, personal information that you submit for publication on the website will be published on the internet and may be available around the world.
            
            Your Rights
            
            You may instruct us to provide you with any personal information we hold about you.  Provision of such information will be subject to:
            
            the payment of a fee; and
            the supply of appropriate evidence of your identity.
            
            We may withhold such personal information to the extent permitted by law.
            
            You may instruct us not to process your personal information for marketing purposes by email at any time.  
            
            Privacy Statement Update
            
            We may update this privacy statement from time-to-time by posting a new version on our website.  You should check this page occasionally to ensure you are happy with any changes.  
            
            We may also notify you of changes to our privacy statement by email.
            
            Other websites
            
            The website contains links to other websites that are not under the control of and are not maintained by redsleeves.co.uk  We are not responsible for the content or reliability of the linked websites. redsleeves.co.uk provides these links for your convenience only but does not endorse the material on these sites.
            
            
            
            Contact Us
            
            If you have any questions about this privacy statement or our treatment of your personal information, please contact me at www.redsleeves.co.uk/contact/
            
            
            
            
            
            
            
            
            
        </p>
    </div>
    </div>
</div>
<div class="container ">
    <div class="row">
        <div class="col mx-auto">
           
                <h2>Website Cookies Policy</h2>

                <p>This website cookies policy template is based on a free document supplied by The Legal Stop Limited through its website <a href="http://www.thelegalstop.co.uk">Legal Stop</a></p>
                
                
                
                
                <p>
                We use cookies on our website. By using our website you agree to this Policy and you consent to our use of cookies in accordance with the terms of this Policy.
                
                About Cookies
                A cookie is a small file which asks permission to be placed on your computer’s hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.
                
                There are two main kinds of cookies: “session” cookies and “persistent” cookies. Session cookies only last for the duration of users using the website and are deleted from your computer when you close your browser, whereas persistent cookies outlast user sessions and remain stored on your computer until deleted, or until they reach their expiry date.
                
                Cookies on this Website
                We use Session Cookie and Persistent Cookies  on this website.
                
                We use cookies for the following purposes:
                e.g. to recognise your computer when you visit our website
                to improve the website’s usability
                to administer this website
                
                Generally, we use cookies to help us administer this website, to improve the website’s usability and for marketing purposes. We may also use cookies to identify which pages are being used. This helps us analyse data about webpage traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.
                
                Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. 
                
                Cookies do not contain any information that personally identifies you, a cookie in no way gives us access to your computer or any information about you.
                
                We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.
                
                You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.
                
                Third Party Cookies
                We also use third party cookies.
                
                If you use third party cookies please include the paragraph below.
                
                [Third party cookies may be used for the following purposes:
                
                to target advertisements which may be of particular interest to you
                
                
                
                Most browsers allow you to reject all cookies, whilst some browsers allow you to reject just third party cookies.
                
                
                
            
           
            </p>

        </div>
    </div>
</div>
<!-- <div class="container my-5">
    <div class="row">
        <div class="col mx-auto">
            <script type="text/javascript" charset="UTF-8"  data-cookiescriptreport="report" src="//report.cookie-script.com/r/bcb7761e02d4c8b437f905bee4d23169.js"></script>
        </div>
    </div>
</div> -->
{% endblock %}

templates/stats.html
<script src="https://code.highcharts.com/highcharts.js"></script>
<!-- <script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script> -->


  <div id="stats" class="max-w-4xl mx-auto"></div>
 

<script>
    Highcharts.chart('stats', {
        chart:  {
        backgroundColor: {
            linearGradient: [0, 0, 500, 500],
            stops: [
                [0, 'rgb(255, 255, 255, 0.0)'],
                [1, 'rgb(200, 200, 255, 0.0)']
            ]
        },
        type: 'column'
    },
        title: {
            text: 'Mental Health Affects'
        },
        xAxis: {
            categories: {{ issue_series|safe }}
        },
        yAxis: {
            title: {
            text: ''
            }
        },
        tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
        '<td style="padding:0"><b>{point.y:.0f} People</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
        plotOptions: {
        column: {
        pointPadding: 0.2,
        borderWidth: 0
        }
    },
        series: [{
            name: 'Cases per 100',
            data: {{ figure_series }},
            color: 'rgb(29,78,216)',
           
        },]
    });
  </script>