accounts/urls.py
from django.urls import path
from .views import dashboard, user_orders, delete_account

app_name = 'accounts'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('user_orders/', user_orders, name='user_orders'),
    path('delete_account/', delete_account, name='delete_account')
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove, cart_object

app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('items/', cart_detail, name='cart_detail'),
    path('items/data/', cart_object, name='cart-object')
]

orders/urls.py
from django.urls import path
from .views import order_create,  payment_completed, payment_canceled, admin_order_detail, admin_order_pdf, stripe_webhook


app_name='orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    # path('process/', payment_process, name='process'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_canceled, name='canceled'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
    path('webhook/', stripe_webhook, name='webhook'),
]

orders/models.py
from django.db import models
from django.conf import settings
from product.models import Product

class Order(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="order_user")
    first_name  = models.CharField(max_length=255)
    last_name   = models.CharField(max_length=255)
    email       = models.EmailField()
    address     = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=20)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    paid        = models.BooleanField(default=False)
    stripe_id   = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


    def get_stripe_url(self):
        if not self.stripe_id:
            # no payment associated
            return ''
        if '_test_' in settings.STRIPE_API_KEY_HIDDEN:
            # Stripe path for test payments
            path = '/test/'
        else:
            # Stripe path for real payments
            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'

class OrderItem(models.Model):
    order       = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product     = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price       = models.DecimalField(max_digits=10,decimal_places=2)
    quantity    = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"})
        self.fields['last_name'].widget.attrs.update({'class': "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"})
        self.fields['email'].widget.attrs.update({'class': "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"})
        self.fields['address'].widget.attrs.update({'class': "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"})
        self.fields['postal_code'].widget.attrs.update({'class': "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"})
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code']

orders/views.py
from io import BytesIO
import weasyprint
from django.contrib import messages
from django.template.loader import render_to_string
import stripe
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .models import Order, OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from django.conf import settings
stripe.api_key = settings.STRIPE_API_KEY_HIDDEN

@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],quantity=item['quantity'], price=item['price'])
            success_url = request.build_absolute_uri(
            reverse('orders:completed')
            )
            cancel_url = request.build_absolute_uri(
                reverse('orders:canceled')
            )
            session_data = {
                'mode': 'payment',
                'success_url': success_url,
                'cancel_url': cancel_url,
                'line_items': []
            }
            for item in order.items.all():
                session_data['line_items'].append({
                    'name': item.product.name,
                    'amount': int(item.price * Decimal('100')),
                    'currency': 'gbp',
                    'quantity': item.quantity,
                })
            session = stripe.checkout.Session.create(**session_data)
            order.stripe_id = session.payment_intent
            order.save()
            cart.clear()
            request.session['order_id'] = order.id
            return redirect(session.url, code=303)
           
    else:
        form = OrderCreateForm()
    return render(request, 'order/order_create.html', {'cart': cart, 'form': form})
    

def payment_completed(request):
    return render(request, 'order/completed.html')

def payment_canceled(request):
    return render(request, 'order/canceled.html')


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
                    payload,
                    sig_header,
                    settings.STRIPE_WEBHOOK_SECRET)
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        if session['mode'] == 'payment':
            payment_intent_id = session['payment_intent']
            try:
                order = Order.objects.get(stripe_id=payment_intent_id)
            except Order.DoesNotExist:
                return HttpResponse(status=404)
            # mark order as paid
            order.paid = True
            order.save()
            # launch asynchronous task
            # payment_completed.delay(order.id)

    return HttpResponse(status=200)

# stripe login
# stripe listen --forward-to localhost:8000/orders/webhook/

def order_created(order_id):
    order = Order.objects.get(id=order_id)
    subject =   f'Order number {order.id}'
    message =   f'Dear {order.first_name},\n\n' \
                f'You have successfully placed an order.' \
                f'Your order ID is {order.id}.'
    mail_sent = send_mail(subject, message, 'eoceanweb@gmail.com', [order.email])
    return mail_sent

# def payment_completed(order_id):
#     order = Order.objects.get(id=order_id)
#     subject = f'MHA = Invoice no. {order.id}'
#     message = 'Please find attached the invoice for your recent purchase'
#     email = EmailMessage(subject, message, 'eoceanweb@gmail.com',[order.email])
#     html = render_to_string('order/pdf.html', {'order':order})
#     out = BytesIO()
#     stylesheets=[weasyprint.CSS(filename= 'static/css/pdf.css')]
#     weasyprint.HTML(string=html).write_pdf(out, stylesheets=stylesheets)
#     email.attach(f'order{order.id}.pdf',
#     out.getvalue(),'application/pdf')
#     email.send()



@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order/detail.html', {'order': order})

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,stylesheets=[weasyprint.CSS(filename = 'static/css/pdf.css')])
        
    return response







# def payment_process(request):
#     order_id = request.session.get('order_id', None)
#     order = get_object_or_404(Order, id=order_id)

#     if request.method == "POST":
#         success_url = request.build_absolute_uri(
#             reverse('order:completed')
#         )
#         cancel_url = request.build_absolute_uri(
#             reverse('order:canceled')
#         )
#         session_data = {
#             'mode': 'payment',
#             'success_url': success_url,
#             'cancel_url': cancel_url,
#             'line_items': []
#         }
#         for item in order.items.all():
#             session_data['line_items'].append({
#                 'name': item.product.name,
#                 'amount': int(item.price * Decimal('100')),
#                 'currency': 'gbp',
#                 'quantity': item.quantity,
#             })
#         session = stripe.checkout.Session.create(**session_data)
#         order.stripe_id = session.payment_intent
#         order.save()

#         return redirect(session.url, code=303)
#     else:
#         return render(request, 'order/process.html')

templates/order/completed.html
{% extends "account/base.html" %}

{% block title %}Payment successful{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto border p-12 text-center text-gray-600 rounded-md shadow-xl">
  <h1><svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>Your payment was successful</h1>
  <a href="{% url 'accounts:user_orders' %}" class="text-gray-600 text-lg hover:text-green-800">View Your Order/Get Product Download</a>
  
 
</div>
{% endblock %}

templates/order/order_create.html
{% extends 'account/base.html' %}
{% block content %}
<div class="max-w-3xl mx-auto  text-gray-600 p-12 ">
    <h1 class=" text-4xl  text-center">Order</h1>
    <div class="grid grid-cols-2 p-6">
        
        <div class="mx-6">
            <form method="POST" class="flex flex-col"  >
                {{ form }}
                {% csrf_token %}
                <input value="Place Order" type="submit" class="my-12 flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">
            </form>
        </div>
        <div class="bg-blue-100 p-6 mx-6 rounded text-lg outline-double">

            <h2 class="text-2xl">Your Order</h2>
            {% for item in cart %}
            <p class="my-4">{{ item.quantity }} x {{ item.product.name }}</p>
            <p>£{{ item.total_price  }}</p>
            {% endfor %}
            
        </div>
    </div>
</div>


{% endblock %}

templates/order/pdf.html
<html>
<body>
  <h1>Mental Health Awareness Course</h1>
  <p>
    Invoice no. {{ order.id }}<br>
    <span class="secondary">
      {{ order.created|date:"d M Y" }}
    </span>
  </p>
  <h3>Bill to:</h3>
  
    <ul>
        <li>{{ order.first_name }} <span>{{ order.last_name }}</span></li>
        <li>{{ order.email }}</li>
        <li>{{ order.address }}</li>
        <li>{{ order.county }}</li>
        <li>{{ order.post_code }}</li>
    </ul>
  
  <h3>Purchased Items:</h3>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Cost</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row">
          <td>{{ item.product.name }}</td>
          <td class="">£{{ item.price|floatformat:2 }}</td>
          <td class="">{{ item.quantity }}</td>
          <td class="">£{{ item.price|floatformat:2}}</td>
        </tr>
      {% endfor %}

      {% if order.coupon %}
        <tr class="subtotal">
          <td colspan="3">Subtotal</td>
          <td >
            £{{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td colspan="3">
            "{{ order.coupon.code }}" coupon
            ({{ order.discount }}% off)
          </td>
          <td class="num neg">
            - £{{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      
      <tr class="total">
        <td colspan="3">Total</td>
        <td class="num">£{{ order.get_total_cost|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
  </span>
</body>
</html>

templates/order/process.html
{% extends "account/base.html" %}
{% load static %}

{% block title %}Pay your order{% endblock %}

{% block content %}
<div class="max-w-3xl mx-auto bg-gray-100 text-gray-600 p-12 rounded-md mb-48">
    <h1 class=" text-4xl  text-center">Order</h1>
    <div class="grid grid-cols-2 p-6 border">
        
        <div class="mx-6">
            <form method="POST" action="{% url 'orders:process' %}" class="flex flex-col">
                {{ form }}
                {% csrf_token %}
                <input value="Pay" type="submit" class="my-12 flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">
            </form>
        </div>
        <div class="bg-gray-300 p-6 mx-6 rounded">

            <h2 class="text-lg">Your Order</h2>
            {% for item in cart %}
            <p class="my-4">{{ item.quantity }} x {{ item.product.name }}</p>
            <p>£{{ item.total_price  }}</p>
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock %}